name: build_docker

on:
  push:
    branches: [ main ]

jobs:
  build_docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: replace latest to tag
        run: |
          sed -i "s/latest/main/g" ./Dockerfile
          cat ./Dockerfile

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: xhofe/alist-aria2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: xhofe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
